# Logistic Regression with Python

## Objectives

After completing this lab, you will be able to:

* Use Logistic Regression for classification
* Preprocess data for modeling
* Implement Logistic regression on real world data

## Classification with Logistic Regression

### Scenario
Assume that you are working for a telecommunications company which is concerned about the number of customers leaving their land-line business for cable competitors. They need to understand who is more likely to leave the company.

###  Load the Telco Churn data 
Telco Churn is a hypothetical data file that concerns a telecommunications company's efforts to reduce turnover in its customer base. Each case corresponds to a separate customer and it records various demographic and service usage information. Before you can work with the data, you must use the URL to get the ChurnData.csv.

### About the dataset
We will use a telecommunications dataset for predicting customer churn. This is a historical customer dataset where each row represents one customer. The data is relatively easy to understand, and you may uncover insights you can use immediately. Typically it is less expensive to keep customers than acquire new ones, so the focus of this analysis is to predict the customers who will stay with the company. 
<br><br>
This data set provides you information about customer preferences, services opted, personal details, etc. which helps you predict customer churn.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import requests

In [2]:
def download (url, fileName):
    response = requests.get(url)
    if (response.status_code ==200):
        with open(fileName,"wb") as f:
            f.write(response.content)

In [3]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/ChurnData.csv"
file_name = 'ChurnData.csv'

In [4]:
download (url, file_name)

In [6]:
df_churn = pd.read_csv(file_name)
df_churn.head()

   tenure   age  address  income   ed  ...  loglong  logtoll  lninc  custcat  churn
0    11.0  33.0      7.0   136.0  5.0  ...    1.482    3.033  4.913      4.0    1.0
1    33.0  33.0     12.0    33.0  2.0  ...    2.246    3.240  3.497      1.0    1.0
2    23.0  30.0      9.0    30.0  1.0  ...    1.841    3.240  3.401      3.0    0.0
3    38.0  35.0      5.0    76.0  2.0  ...    1.800    3.807  4.331      4.0    0.0
4     7.0  35.0     14.0    80.0  2.0  ...    1.960    3.091  4.382      3.0    0.0

[5 rows x 28 columns]

# Data Preprocessing

For this lab, we can use a subset of the fields available to develop out model. Let us assume that the fields we use are 'tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip' and of course 'churn'.

In [7]:
churn_df = df_churn[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip','churn']]
churn_df.head()

   tenure   age  address  income   ed  employ  equip  churn
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0    1.0
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0    1.0
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0    0.0
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0    0.0
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0    0.0

In [9]:
churn_df[['churn']] = churn_df[['churn']].astype('int')
churn_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   tenure   200 non-null    float64
 1   age      200 non-null    float64
 2   address  200 non-null    float64
 3   income   200 non-null    float64
 4   ed       200 non-null    float64
 5   employ   200 non-null    float64
 6   equip    200 non-null    float64
 7   churn    200 non-null    int64
dtypes: float64(7), int64(1)
memory usage: 12.6 KB

For modeling the input fields X and the target field y need to be fixed. Since that the target to be predicted is 'churn', the data under this field will be stored under the variable 'y'. We may use any combination or all of the remaining fields as the input. Store these values in the variable 'X'.

In [11]:
y = np.asarray(churn_df['churn'])
X = np.asarray(churn_df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip','churn']])

print("First 5 data rows of y: \n",y[0:5])
print("First 5 data rows od X: \n", X[0:5])

First 5 data rows of y:
 [1 1 0 0 0]
First 5 data rows od X:
 [[ 11.  33.   7. 136.   5.   5.   0.   1.]
 [ 33.  33.  12.  33.   2.   0.   0.   1.]
 [ 23.  30.   9.  30.   1.   2.   0.   0.]
 [ 38.  35.   5.  76.   2.  10.   1.   0.]
 [  7.  35.  14.  80.   2.  15.   0.   0.]]

## Standardization

It is also a norm to standardize or normalize the dataset in order to have all the features at the same scale. This helps the model learn faster and improves the model performance. We may make use of StandardScalar function in the Scikit-Learn library.

In [13]:
Scaler = StandardScaler()

X_scale = Scaler.fit_transform(X)
print("First 5 rows of X_scale: \n",X_scale[0:5])

First 5 rows of X_scale:
 [[-1.13518441 -0.62595491 -0.4588971   0.4751423   1.6961288  -0.58477841
  -0.85972695  1.56469673]
 [-0.11604313 -0.62595491  0.03454064 -0.32886061 -0.6433592  -1.14437497
  -0.85972695  1.56469673]
 [-0.57928917 -0.85594447 -0.261522   -0.35227817 -1.42318853 -0.92053635
  -0.85972695 -0.63910148]
 [ 0.11557989 -0.47262854 -0.65627219  0.00679109 -0.6433592  -0.02518185
   1.16316    -0.63910148]
 [-1.32048283 -0.47262854  0.23191574  0.03801451 -0.6433592   0.53441472
  -0.85972695 -0.63910148]]